# Welcome to Jekyll!
#

# Site settings
title: Paiara Pedone
description: |
  Casa Vacanza  
  San Gregorio, (Patu) Provincia di Lecce  
  
owner: Paiara Pedone # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: casaoialura@gmail.com
baseurl: "/oialura" # the subpath of your site, e.g. /blog
url: "http://spmaps.github.io/oialura/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/paiarapedone
  github: https://github.com/oialura
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/paiarapedone
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
